name: PrimaryDecomposition
version: "2020.04.17"
license: "GPL-2.0-or-later"
date: 2020-10-17
description: |
    Tools for primary decomposition

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Eva Maria Hemmerling
      url: https://github.com/HemEM/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2013.11.06"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "RingsForHomalg"
      version: ">= 2020.04.17"
      url: "https://homalg-project.github.io/homalg_project/RingsForHomalg"
    - name: "GaussForHomalg"
      version: ">= 2013.06.26"
      url: "https://homalg-project.github.io/homalg_project/GaussForHomalg"
    - name: "MatricesForHomalg"
      version: ">= 2019.09.01"
      url: "https://homalg-project.github.io/homalg_project/MatricesForHomalg"
    - name: "Modules"
      version: ">= 2019.09.01"
      url: "https://homalg-project.github.io/homalg_project/Modules"
    - name: "GradedModules"
      version: "2013.09.30"
      url: "https://homalg-project.github.io/homalg_project/GradedModules"
    - name: "GAPDoc"
      version: ">= 1.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://homalg-project.github.io/PrimaryDecomposition
readme: README.md
packageinfo: https://homalg-project.github.io/PrimaryDecomposition/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/PrimaryDecomposition/releases/download/v2020.04.17/PrimaryDecomposition-2020.04.17.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/PrimaryDecomposition/releases/download/v2020.04.17/PrimaryDecomposition-2020.04.17.zip

pdf: https://github.com/homalg-project/PrimaryDecomposition/releases/download/v2020.04.17/PrimaryDecomposition-2020.04.17.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    primary decomposition, radical ideal, prime decomposition, associated primes, embedded primes.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BH20</span>]   <b class='BibAuthor'>Barakat, M. and Hemmerling, E. M.</b>,
     <i class='BibTitle'>PrimaryDecomposition, Tools for primary decomposition,
             Version 2020.04.17</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/PrimaryDecomposition">https://homalg-project.github.io/PrimaryDecomposition</a></span>.
    </p>
    

bibtex: |
    @misc{ PrimaryDecomposition2020.04.17,
      author =           {Barakat, M. and Hemmerling, E. M.},
      title =            {{PrimaryDecomposition},      Tools     for     primary
                          decomposition, {V}ersion 2020.04.17},
      month =            {Oct},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/PrimaryDecomposition}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{PrimaryDecomposition}}},
      keywords =         {primary    decomposition;    radical    ideal;   prime
                          decomposition; associated primes; embedded primes},
      printedkey =       {BH20}
    }

