name: PrimaryDecomposition
version: "2022.04-01"
license: "GPL-2.0-or-later"
date: 2022-04-26
description: |
    Tools for primary decomposition

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Eva Maria Hemmerling
      url: https://github.com/HemEM/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io

GAP: ">= 4.11.1"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2013.11.06"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "RingsForHomalg"
      version: ">= 2020.04.17"
      url: "https://homalg-project.github.io/pkg/RingsForHomalg"
    - name: "GaussForHomalg"
      version: ">= 2013.06.26"
      url: "https://homalg-project.github.io/pkg/GaussForHomalg"
    - name: "MatricesForHomalg"
      version: ">= 2019.09.01"
      url: "https://homalg-project.github.io/pkg/MatricesForHomalg"
    - name: "Modules"
      version: ">= 2019.09.01"
      url: "https://homalg-project.github.io/pkg/Modules"
    - name: "GradedModules"
      version: "2013.09.30"
      url: "https://homalg-project.github.io/pkg/GradedModules"
    - name: "GAPDoc"
      version: ">= 1.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://homalg-project.github.io/pkg/PrimaryDecomposition
readme: README.md
packageinfo: https://homalg-project.github.io/PrimaryDecomposition/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/PrimaryDecomposition/releases/download/v2022.04-01/PrimaryDecomposition-2022.04-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/PrimaryDecomposition/releases/download/v2022.04-01/PrimaryDecomposition-2022.04-01.zip

pdf: https://github.com/homalg-project/PrimaryDecomposition/releases/download/v2022.04-01/PrimaryDecomposition-2022.04-01.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    primary decomposition, radical ideal, prime decomposition, associated primes, embedded primes.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BH22</span>]   <b class='BibAuthor'>Barakat, M. and Hemmerling, E. M.</b>,
     <i class='BibTitle'>PrimaryDecomposition, Tools for primary decomposition,
             Version 2022.04-01</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/PrimaryDecomposition">https://homalg-project.github.io/pkg/PrimaryDecomposition</a></span>.
    </p>
    

bibtex: |
    @misc{ PrimaryDecomposition2022.04-01,
      author =           {Barakat, M. and Hemmerling, E. M.},
      title =            {{PrimaryDecomposition},      Tools     for     primary
                          decomposition, {V}ersion 2022.04-01},
      month =            {Apr},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/PrimaryDecomposition}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{PrimaryDecomposition}}},
      keywords =         {primary    decomposition;    radical    ideal;   prime
                          decomposition; associated primes; embedded primes},
      printedkey =       {BH22}
    }

