#############################################################################
##
##  RadicalComputation.gd                       PrimaryDecomposition package
##
##  Copyright 2013,      Mohamed Barakat, University of Kaiserslautern
##                  Eva Maria Hemmerling, University of Kaiserslautern
##
##  Declaration of some functions for radical computation.
##
#############################################################################

#! @Chapter Radical Computation

####################################
#
#! @Section Attributes
#
####################################

#! @Description
#!  Computes the radical of an ideal if the coefficients field is perfect
#!  and otherwise computes the FGLM data of the ideal <M>J</M> which is
#!  generated by the separable parts of the minimal polynomials of the
#!  indeterminates evaluated for the indeterminates of the ring.
#! @Arguments I
#! @Returns a LeftSubmodule
DeclareAttribute( "PreparationForRadicalOfIdeal",
	IsHomalgModule );

#! @Description
#!  Computes the radical of a zero dimensional ideal <A>I</A>. 
#! @Arguments I
#! @Returns a LeftSubmodule
DeclareAttribute( "RadicalOfIdeal",
	IsHomalgModule );
#! @InsertSystem RadicalOfIdeal

#! @Arguments mu
#! @Returns a matrix
#! @Description
#!  Computes the companion matrix of the monic univariate polynomial <A>mu</A>
#!  over a univariate ring.
DeclareAttribute( "CompanionMatrix",
        IsHomalgRingElement );
#! @InsertSystem CompanionMatrix
