#############################################################################
##
##  Tools.gd                                    PrimaryDecomposition package
##
##  Copyright 2013,      Mohamed Barakat, University of Kaiserslautern
##                  Eva Maria Hemmerling, University of Kaiserslautern
##
##  Declaration of some tools.
##
#############################################################################

#! @Chapter Tools

####################################
#
#! @Section Attributes
#
####################################

#! @Description
#!  Computes a basis of the ring <A>R</A>,
#!  provided it is free of finite rank over its coefficients ring.
#! @Arguments R
#! @Returns a &homalg; matrix
DeclareAttribute( "BasisOverCoefficientsRing",
        IsHomalgRing );
#! @InsertSystem BasisOverCoefficientsRing

#! @Description
#!  Computes a representation matrix of the ring element <A>r</A>,
#!  provided it is free of finite rank over its coefficients ring.
#! @Arguments r
#! @Returns a &homalg; matrix
DeclareAttribute( "RepresentationOverCoefficientsRing",
        IsHomalgRingElement );
#! @InsertSystem RepresentationOverCoefficientsRing

#! @Description
#!  Computes the FGLM data of the ring <A>R</A> (see <Cite Key="SJ"/>),
#!  provided it is free of finite rank over its coefficients ring.
#!  The FGLM data of such a ring consists of the representation matrices
#!  of all indeterminates of <A>R</A> computed by BasisOverCoefficientsRing.
#! @Arguments R
#! @Returns a list
DeclareAttribute( "FGLMdata",
        IsHomalgRing );
#! @InsertSystem FGLMdata

#! @Description
#!  Computes the minimal polynomial of the element <A>r</A>
#!  of a ring <M>R</M> of finite rank over its coefficients ring.
#! @Arguments r
#! @Returns a matrix
# @InsertChunk MinimalPolynomial_ring_element
#! @Group MinimalPolynomial
DeclareAttribute( "MinimalPolynomial",
	IsHomalgRingElement );
#! @InsertSystem MinimalPolynomial

#! @Description
#!  Computes the irreducible factors of the square free part of the 
#!  univariate polynomial <A>p</A>.
#! @Arguments p
#! @Returns a list
DeclareAttribute( "SquareFreeFactors",
	IsHomalgRingElement );
#! @InsertSystem SquareFreeFactors

#! @Description
#!  Computes the separable part of a univariate polynomial <A>p</A>.
#! @Arguments p
#! @Returns a ring element
DeclareAttribute( "SeparablePart",
	IsHomalgRingElement );
#! @InsertSystem SeparablePart

#! @Arguments r
#! @Returns a matrix
#! @Description
#!  Computes the coefficients of the basis representation of the ring element
#!  <A>r</A>, provided the ring is free of finite rank over its coefficients ring.
DeclareAttribute( "BasisCoefficientsOfRingElement", 
	IsHomalgRingElement);
#! @InsertSystem BasisCoefficientsOfRingElement

#! @Arguments G
#! @Returns a matrix
#! @Description
#!  Computes the basis of an ideal generated by the entries of <A>G</A>,
#!  over the coefficient ring.
DeclareOperation( "IdealBasisOverCoefficientRing", 
	[ IsHomalgMatrix ] );
#! @InsertSystem IdealBasisOverCoefficientsRing

#! @Arguments K
#! @Returns a ring
#! @Description
#!  Computes an isomorphic, GAP internal ring.
DeclareAttribute( "GapInternalIsomorphicRing",
	IsHomalgRing);

#! @Arguments M
#! @Returns a list
#! @Description
#!  Computes a Groebner Basis of an ideal which is defined by a basis over the
#!  coefficients ring provided the ideal lies in a ring which is free of finite
#!  rank over its coefficients ring. The basis elements are given in the rows
#!  of the matrix <A>M</A> in form of coefficient vectors with respect 
#!  to the basis of the ring, which is computed by BasisOverCoefficientsRing.
DeclareAttribute( "IdealBasisToGroebner", 
	IsHomalgMatrix);

#! @Arguments G
#! @Returns a matrix
#! @Description
#!  Computes a Groebner Basis of the ideal generated by the 
#!  entries of the matrix <A>G</A> and the generators of the defining zero 
#!  dimensional ideal of the residue class ring.
DeclareAttribute( "AppendToGroebnerBasisOfZeroDimensionalIdeal", 
	IsHomalgMatrix );
#! @InsertSystem AppendToGroebnerBasisOfZeroDimensionalIdeal
	
#! @Arguments f
#! @Returns a ring element
#! @Description
#!  Computes the derivative of the univariate polynomial <A>f</A>.
DeclareAttribute( "Derivative", 
	IsHomalgRingElement);
#! @InsertSystem Derivative

####################################
#
#! @Section Operations
#
####################################

#! @Arguments r, str
#! @Group MinimalPolynomial
DeclareOperation( "MinimalPolynomial",
	[ IsHomalgRingElement, IsString ] );

#! @Arguments r, t
#! @Group MinimalPolynomial
DeclareOperation( "MinimalPolynomial",
	[ IsHomalgRingElement, IsHomalgRingElement ] );

#! @Description
#!  Determines whether <A>lambda</A> is contained in any <M>n - 1 </M> dimensional 
#!  subspace spanned by the rows of  <A>L</A>.
#! @Arguments lambda, L
#! @Returns a matrix
DeclareOperation( "IsNotContainedInAnyHyperplane",
	[IsHomalgMatrix, IsHomalgMatrix ] );
#! @InsertSystem IsNotContainedInAnyHyperplane
	
#! @Description
#!  Generates an element, which is not contained in any <M>n - 1 </M> 
#!  dimensional subspace of the vector field <M>K^n</M> over its ground
#!  field or respectively <M>C^n</M> spanned by the rows of <A>L</A>.
#! @Arguments L
#! @Returns a value
DeclareOperation( "GeneratorOfAnElementNotContainedInAnyHyperplane",
	[ IsHomalgMatrix ] );
#! @InsertSystem GeneratorOfAnElementNotContainedInAnyHyperplane

#! @Arguments L, C
#! @Returns a value
DeclareOperation( "GeneratorOfAnElementNotContainedInAnyHyperplane",
	[ IsHomalgMatrix, IsHomalgRing ] );

#! @Arguments M, e
#! @Returns two lists
#! @Description
#!  Computes a basis of the residue class ring and a Groebner Basis of the
#!  defining ideal, both defined by the FGLM data <A>M</A> and the identity 
#!  element <A>e</A>.
DeclareOperation( "FGLMToGroebner", 
	[ IsList, IsHomalgMatrix ] );
#! @InsertSystem FGLMToGroebner

#! @Arguments M, e, l
#! @Returns two lists
DeclareOperation( "FGLMToGroebner", 
	[ IsList, IsHomalgMatrix, IsList ] );
